name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Triggers the workflow when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Triggers the workflow for pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the operating system for the runner (Ubuntu in this case)

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Set the Python version for your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install your dependencies from requirements.txt

      # Step 4: Run tests (Optional)
      - name: Run tests
        run: |
          # If you have tests, you can use pytest to run them
          echo "No tests to run"

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ai-code-review .  # Build the Docker image for your project

      # Step 6: Log in to Docker Hub (if you're pushing to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Push Docker image to Docker Hub (Optional)
      - name: Push Docker image to Docker Hub
        run: |
          docker push ai-code-review  # Push the Docker image to Docker Hub

      # Step 8: Deployment (Optional)
      # You can add steps here to deploy your app to a cloud provider (e.g., AWS, GCP, or Heroku).
